name: multi-client-api

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elastic01
    environment:
      - node.name=elastic01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_EMAIL: valentin@mail.com
    build:
      context: .
      dockerfile: psgr.dockerfile
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # command: ["log_statement=all"]
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  es01:
    driver: local